from __future__ import annotations


DEFAULT_INITIAL_EQUITY = 100_000.0
DEFAULT_RISK_PER_TRADE_PCT = 0.01
DEFAULT_MAX_POSITION_PCT = 0.20
DEFAULT_HARD_STOP_PCT = 0.04
DEFAULT_FIRST_TARGET_R = 1.0
DEFAULT_WEAK_REGIME_SIZE_MULTIPLIER = 0.50
DEFAULT_MIN_PULLBACK_PCT = 0.01
DEFAULT_MAX_PULLBACK_PCT = 0.06
DEFAULT_MIN_SCORE = 7.0
